### ISSUE TITLE
Unable to insert 0 and F values

### ISSUE THREAD

**Issue by mkondratek** [thomoncik/hexadoku#33]
Scenario:
1. Go to: New game -> Hexadoku
2. Choose some cell
3. Click **m** to insert new value
4. Click **0** or **F**

Expected:
Required value appear in the cell.

Actual:
Required value does not appear in the cell.

Possible bug location:
https://github.com/thomoncik/hexadoku/blob/1e2d390a53838b0d44593eea6f07a9111713c876/src/InsertionPlayState.cpp#L13

Possible bug solution:
Add symbols '0' and 'f' to the vector.

**Comment by thomoncik** [comment]
Fixed in 7f3e61f
