### ISSUE TITLE
Highlighting marks empty value as incorrect one with red background.

### ISSUE THREAD

**Issue by mkondratek** [thomoncik/hexadoku#47]
Way to reproduce: 
1. Start new game (standard/hexadoku)
2. Insert value ' ' (space)

Result:
cell is marked as incorrect

Expected:
no change

**Comment by kkiermasz** [comment]
https://github.com/thomoncik/hexadoku/pull/53

**Comment by kkiermasz** [comment]
@mkondratek fixed in #53
